version: "3"
services:
  backend:
    container_name: movie_back
    build:
      context: "./server"
      dockerfile: Dockerfile
    command: npm run start
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    container_name: movie_front
    build: "./client"
    command: yarn start
    volumes:
      - ./client:/app
    depends_on:
      - backend
    ports:
      - "3000:3000"
  db:
    container_name: movie_db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment: 
      - POSTGRES_DB=challenge
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres