version: "3.7"
services:
  backend:
    container_name: movie_back
    build:
      context: "./server"
      dockerfile: Dockerfile
    command: npm run start
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "8000:8000"
    environment:
      - EXTERNAL_PORT=8000
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=challenge
      - PGHOST=db # NAME OF THE SERVICE
    depends_on:
      - db
  frontend:
    container_name: movie_front
    build: 
      context: "./client"
      dockerfile: Dockerfile
    command: yarn start
    volumes:
      - ./client:/app
    depends_on:
      - backend
    ports:
      - "3000:3000"
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 35432:5432
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    environment: 
      - POSTGRES_DB=challenge
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres